# Generated by Django 3.0.5 on 2020-04-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
